spring:
  application:
    name: user-story
  datasource:
    url: jdbc:postgresql://localhost:5432/user-story
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1997
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        show_sql: true
    hibernate:
      ddl-auto: update